### ISSUE TITLE
Issue when adding multiple pinned columns

### ISSUE THREAD

**Issue by juanpablof** [ssuperczynski/ngx-easy-table#235]
Thank you for releasing 9.4.0. I just wanted to chime in and tell you that I gave it a try and I had the following error: 

- When adding more than two columns, there seems to be a space calculated in between tables (screenshot attached). If you see the screenshot below, "Name" is underneath "Company". I'm using your example in my code. The table header is blue because I just applied my own style but it doesn't affect the general behaviour of the table.

![Screen Shot 2019-05-07 at 3 32 55 PM](https://user-images.githubusercontent.com/790922/57327735-9e740e00-70dd-11e9-97d6-f6746de8b6fd.png)

If you have a chance, please have a look. I'll try to debug the code a bit more and let you know if I find the root cause. Thanks again!

Here is a video: 
[VIDEO-error-when-scrolling-horizontally.mp4.zip](https://github.com/ssuperczynski/ngx-easy-table/files/3154268/VIDEO-error-when-scrolling-horizontally.mp4.zip)

**Comment by ssuperczynski** [comment]
Yes, this is because table has `display: block;` instead `display: table;` when using horizontal scroll. I've set width of pinned column to 150px, tried to fix it but it requires tons of calculation to display it correctly, so that's the reason of hardcoded width.
I've added https://ngx-easy-table.eu/#/column-class as a helper, if you could define column class with some known `left` property it will fix this issue. For example

```scss
.calculated-position {
  left: 200px;
}
```

```ts
this.columns = [
      { key: 'phone', title: 'Phone' },
      { key: 'age', title: 'Age' },
{ key: 'company', title: 'Company', pinned: true, cssClass: { includeHeader: true, name: 'calculated-position' } },
      { key: 'address.number', title: 'Number' },
      { key: 'name', title: 'Name' },
      { key: 'isActive', title: 'STATUS' },
    ];
```

This is not prefect solution, but for now I'don't see better one without making lot of calculations, but help is always welcome 🌻

**Comment by juanpablof** [comment]
Great! Thanks Sebastian. I will give it a try. I will also try to fix it on my free time. If I do, I'll send you a pull request.
